#!/bin/bash
# Process start
echo "- [INFO] - $(date +"%Y-%m-%d-%H-%M-%S") - Starting auto-save process."
echo "- [INFO] - $(date +"%Y-%m-%d-%H-%M-%S") - Creating branch name."
# Obtains the current date for the branch name
timestamp=$(date +"%Y-%m-%d-%H-%M-%S")
# Creates the branch name
branch_name="bds-auto-save/${GITLAB_USER_EMAIL}/$timestamp" 
echo "$branch_name"
echo ""
echo "- [INFO] - $(date +"%Y-%m-%d-%H-%M-%S") - Executing git status --porcelain."
# Opens the workspace directory
cd ${HOME}/workspace
# Obtains changes from git
git_status_response=$(git status --porcelain)
if [ -z "${git_status_response}" ]
then
    echo ""
else
    echo "${git_status_response}"
    echo ""
fi

echo "- [INFO] - $(date +"%Y-%m-%d-%H-%M-%S") - Validating pending changes."
if [ -z "${git_status_response}" ]
then # No pending changes
    echo "- [INFO] - $(date +"%Y-%m-%d-%H-%M-%S") - There are NO pending changes."
else # There are pending changes
    echo "- [INFO] - $(date +"%Y-%m-%d-%H-%M-%S") - There are pending changes."
    echo ""
    echo "- [INFO] - $(date +"%Y-%m-%d-%H-%M-%S") - Creating new branch."
    git checkout -b $branch_name
    echo ""
    echo "- [INFO] - $(date +"%Y-%m-%d-%H-%M-%S") - Adding files to stage."
    git add --all
    echo ""
    echo "- [INFO] - $(date +"%Y-%m-%d-%H-%M-%S") - Creating commit."
    git commit -m 'Auto save generated by BlackDiamond studio'
    echo ""
    echo "- [INFO] - $(date +"%Y-%m-%d-%H-%M-%S") - Pushing to repository."
    git push --force origin $branch_name
    echo ""
    echo "- [INFO] - $(date +"%Y-%m-%d-%H-%M-%S") - Reporting auto-save."
    
fi
echo ""
echo "- [INFO] - $(date +"%Y-%m-%d-%H-%M-%S") - Auto-save process finished."