CREATE TABLE StringTable
(
	COL1 [CHAR] DEFAULT 'HELLO',
	COL2 [CHAR](5),
	COL3 [VARCHAR] COLLATE Modern_Spanish_CI_AI DEFAULT 'HOLA' NOT NULL,
	COL4 [VARCHAR](max) COLLATE Latin1_General_CI_AI DEFAULT 'HOLA' NOT NULL,
-- Unicode character strings
	COL5 [NVARCHAR],
	COL6 [NVARCHAR](15)
);