CREATE OR ALTER PROCEDURE ERROR_PROCEDURE AS
BEGIN
	BEGIN TRY
		DECLARE @VAR INT = 0;
		SELECT 1/@VAR;
	END TRY
	BEGIN CATCH
		SELECT * INTO ERROR_TABLE FROM 
		(SELECT
			ERROR_NUMBER() AS ERROR_NUMBER,
			ERROR_SEVERITY() AS ERROR_SEVERITY,
			ERROR_STATE() AS ERROR_STATE,
			ERROR_PROCEDURE() AS ERROR_PROCEDURE,
			ERROR_LINE() AS ERROR_LINE,
			ERROR_MESSAGE() AS ERROR_MESSAGE
		) error_query;
	END CATCH
END;