CREATE OR ALTER PROCEDURE NumericProcedure2 @Clean BIT AS
BEGIN
	DECLARE @VALUE1 AS VARCHAR = 'A';

	Declares:
	DECLARE @VALUE2 INT;
	SET @VALUE2 = 1;

	BeginTry:

	BEGIN TRY
		CREATE TABLE NumericProcedure2Table
		(
			COL1 VARCHAR,
			COL2 SMALLINT
		);

		DECLARE CUSTOM_CURSOR CURSOR FOR SELECT COL8 FROM NumericTable;
		DECLARE @VALUE3 AS SMALLINT = 1;
		OPEN CUSTOM_CURSOR;
		
		FETCH NEXT FROM CUSTOM_CURSOR INTO @VALUE3;
		INSERT INTO NumericProcedure2Table SELECT CHAR(ASCII(@VALUE1) + @VALUE2), @VALUE3;
		SET @VALUE2 += 1;

		FETCH NEXT FROM CUSTOM_CURSOR INTO @VALUE3;
		INSERT INTO NumericProcedure2Table SELECT CHAR(ASCII(@VALUE1) + @VALUE2), @VALUE3;
		SET @VALUE2 += 1;

		FETCH NEXT FROM CUSTOM_CURSOR INTO @VALUE3;
		INSERT INTO NumericProcedure2Table SELECT CHAR(ASCII(@VALUE1) + @VALUE2), @VALUE3;
		SET @VALUE2 += 1;

		FETCH NEXT FROM CUSTOM_CURSOR INTO @VALUE3;
		INSERT INTO NumericProcedure2Table SELECT CHAR(ASCII(@VALUE1) + @VALUE2), @VALUE3;
		SET @VALUE2 += 1;

		IF @Clean = 1
			GOTO Cleanup

		GOTO NotCleanup
	END TRY
	
	BEGIN CATCH
		GOTO Cleanup
	END CATCH

	NotCleanup:
	GOTO Finished

	Finished:
	Return 1

	Cleanup:
	CLOSE CUSTOM_CURSOR;
	DEALLOCATE CUSTOM_CURSOR;
	GOTO Finished
END;