CREATE OR ALTER PROCEDURE OBJECT_ID_PROCEDURE AS
BEGIN
	SELECT OBJECT_ID('PUBLIC.function1', 'F');
	IF OBJECT_ID(N'CONVERT_PROCEDURE', 'P') IS NOT NULL
	BEGIN
		SELECT * INTO OBJECT_ID_TABLE FROM (SELECT 1 AS COL1) object_id_query;
	END;
	ELSE
	BEGIN
		SELECT * INTO OBJECT_ID_TABLE FROM (SELECT 0 AS COL1) object_id_query;
	END;
END;