CREATE OR ALTER PROCEDURE ERROR_PROCEDURE AS
BEGIN
	BEGIN TRY
		DECLARE @VAR INT = 0;
		SELECT 1/@VAR;
	END TRY
	BEGIN CATCH
		SELECT * INTO ERROR_TABLE FROM 
		(SELECT
			ERROR_NUMBER() AS ERROR_NUMBER,
			ERROR_SEVERITY() AS ERROR_SEVERITY,
			ERROR_STATE() AS ERROR_STATE,
			ERROR_PROCEDURE() AS ERROR_PROCEDURE,
			ERROR_LINE() AS ERROR_LINE,
			ERROR_MESSAGE() AS ERROR_MESSAGE
		) error_query;
	END CATCH
END;

GO

-- query1
EXEC ERROR_PROCEDURE;

GO

CREATE OR ALTER PROCEDURE COALESCE_PROCEDURE AS
BEGIN
	SELECT * INTO COALESCE_TABLE FROM
	(SELECT COALESCE ((SELECT NULL), NULL, 10 ) AS COL1) coalesce_query;
END;

GO

-- query2
EXEC COALESCE_PROCEDURE;

GO

CREATE OR ALTER PROCEDURE CONVERT_PROCEDURE AS
BEGIN
	DECLARE @VAR VARCHAR(3) = '999';
	SELECT * INTO CONVERT_TABLE FROM
	(SELECT CONVERT (INT, (SELECT @VAR)) + 1 AS COL1) convert_query;
END;

GO

-- query3
EXEC CONVERT_PROCEDURE;

GO

CREATE OR ALTER PROCEDURE OBJECT_ID_PROCEDURE AS
BEGIN
	SELECT OBJECT_ID('PUBLIC.function1', 'F');
	IF OBJECT_ID(N'CONVERT_PROCEDURE', 'P') IS NOT NULL
	BEGIN
		SELECT * INTO OBJECT_ID_TABLE FROM (SELECT 1 AS COL1) object_id_query;
	END;
	ELSE
	BEGIN
		SELECT * INTO OBJECT_ID_TABLE FROM (SELECT 0 AS COL1) object_id_query;
	END;
END;

GO

-- query4
EXEC OBJECT_ID_PROCEDURE;