-- Numeric Table Views
CREATE OR ALTER VIEW NumericTableView1
WITH ENCRYPTION  
AS  
SELECT * FROM NumericTable
WITH CHECK OPTION;

GO

CREATE OR ALTER VIEW NumericTableView2
AS
SELECT TOP 3 * FROM NumericTable;

GO

CREATE OR ALTER VIEW NumericTableView3
AS
SELECT NULL as "NULL", SUM = (NT.COL2 + NT.COL13), CAST(COL7 / COL8 AS DECIMAL(5)) as CASTS, COL14 MAX FROM NumericTable as NT WHERE NT.COL14 = 3442 + 1 GROUP BY NT.COL2, NT.COL7, NT.COL8, NT.COL13, NT.COL14;

GO

-- Date Table Views
CREATE OR ALTER VIEW DateTableView1
AS
SELECT * FROM DateTable;

GO

CREATE OR ALTER VIEW DateTableView2
AS
SELECT *, DATES = DT.COL1 FROM DateTable DT WHERE DT.COL1 = '0001-01-01';

GO

-- String Table Views
CREATE OR ALTER VIEW StringTableView1
AS
SELECT * FROM StringTable;

GO

CREATE OR ALTER VIEW StringTableView2
AS
SELECT COL3 = CAST(ST.COL3 as CHAR) FROM StringTable as ST;